; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; De haber clonado el repositorio,
; no es necesario cambiar el directorio de las librerías a la carpeta lib del proyecto,
; para que PlatformIO pueda encontrarlas.
; en caso de tener la carpeta lib en la raíz del proyecto, es necesario modificar esta sección
; donde se borra o comenta la línea lib_dir, y se deja que PlatformIO busque las librerías en la carpeta lib por defecto.

[platformio]
lib_dir = ../../lib

[env:esp32dev]
platform = espressif32
board = esp32dev #esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200
monitor_filters = default
monitor_rts = 0
monitor_dtr = 0